# Generated by Django 3.0.10 on 2022-02-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('nis', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60)),
                ('password', models.TextField()),
                ('name', models.CharField(blank=True, max_length=36, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
